name: my react workflow

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

  build-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install
        working-directory: ./test

      - name: Build Vite app
        run: npm run build
        working-directory: ./test
      - name: show files 
        run: ls -la
        working-directory: ./test